name: Nightly

on:
  # We run our tests whenever the pom or a source file was touched.
  # There is no need to run Maven when only the changelog was touched.
  # We may also want to re-run this workflow when the workflow file itself
  # was updated too.
  push:
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/workflows/maven.yml'
    branches: [ master ]

  # Whenever someone submits a new pull request which modified the pom or a source file,
  # we want to ensure it compiles successfully and that all tests will pass.
  pull_request:
    paths:
    - 'src/**'
    - 'pom.xml'
    branches: [ master ]

jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:

    # 1. Check out the current working tree
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Java 21 JDK (Adopt)
    - name: Java 21 setup
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '21'

    # 3. Setup local Maven package cache to speed up building
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # 4. Build via Maven 
    - name: Build via Maven
      run: mvn verify -B --file pom.xml -DdisableXmlReport=true

    # 5. Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/HothGeneratorReload/HothGeneratorReload/target/
